/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AImage: typeof import('./../src/components/AImage.vue')['default']
    BigDataCheckboxGroup: typeof import('./../src/components/BigDataCheckboxGroup/index.vue')['default']
    CustomLabel: typeof import('./../src/components/BigDataCheckboxGroup/CustomLabel.vue')['default']
    'Demo1.story': typeof import('./../src/components/BigDataCheckboxGroup/demo1.story.vue')['default']
    'Demo2.story': typeof import('./../src/components/BigDataCheckboxGroup/demo2.story.vue')['default']
    'Demo5.story': typeof import('./../src/components/BigDataCheckboxGroup/demo5.story.vue')['default']
    IconCommunity: typeof import('./../src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../src/components/icons/IconTooling.vue')['default']
    Index1: typeof import('./../src/components/BigDataCheckboxGroup/index1.vue')['default']
    Index2: typeof import('./../src/components/BigDataCheckboxGroup/index2.vue')['default']
    Index3: typeof import('./../src/components/BigDataCheckboxGroup/index3.vue')['default']
    Index4: typeof import('./../src/components/BigDataCheckboxGroup/index4.vue')['default']
    Index5: typeof import('./../src/components/BigDataCheckboxGroup/index5.vue')['default']
    InjectDemo: typeof import('./../src/components/InjectDemo.vue')['default']
    'InjectDemo.story': typeof import('./../src/components/InjectDemo.story.vue')['default']
    ItemDemo: typeof import('./../src/components/BigDataCheckboxGroup/ItemDemo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./../src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../src/components/WelcomeItem.vue')['default']
  }
}
